version: "3.9"

networks:
  bot_net:
    driver: bridge

secrets:
  tg_token:
    file: tg_token.secret.txt

services:
  backend:
    build:
      context: .
      dockerfile: ./master.Dockerfile
    container_name: videobot_backend
    volumes:
      - ../app/:/root/app
      - /var/www/VideoBot:/var/www/VideoBot
      - /$HOME/.cache/VideoBot_DB:/BOT_DB
    networks:
      - bot_net
    # depends_on:
    #   - postgres
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER:-postgres}
    #   - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    #   - POSTGRES_DB=${POSTGRES_DB:-videobot}
    #   - POSTGRES_HOST=postgres
    #   - POSTGRES_PORT=5432
    secrets:
      # - db_password
      - tg_token
    working_dir: /root/app
    entrypoint: 
      - /bin/bash
      - -c
    command: 
      - make all && videobot
    restart: unless-stopped
